version: 2
registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  github-feed:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Coultard/index.json
    username: ${{ secrets.GH_USERNAME }}
    password: ${{ secrets.GH_PAT }}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - nuget
      - github-feed
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "xunit*"
        update-types: ["version-update:semver-patch"]
    groups:
      dependencies:
        patterns:
          - "*"